name: Build Images
on:
  push:
    tags:
      - 'images/v*'

jobs:
  build:
    name: Build Iamges
    runs-on: ubuntu-latest
    strategy:
        matrix:
            dockerfile:
              - images/protobuf-compiler-go
              - images/protobuf-compiler-go-alpine
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.CR_PAT }}
      - name: Build & Push Image
        uses: docker/build-push-action@v2
        with:
          context: ./images
          file: ${{ matrix.dockerfile }}
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/${{ matrix.dockerfile }}:latest
  
  