
name: Image Build (AMD64)
on:
  workflow_call:
    secrets:
      cr-pat:
        description: 'Personal access token'
        required: true

jobs:
  go-build:
    name: Go Binary & Image Build
    runs-on: ubuntu-latest
    steps:
      - name: Set version tag
        id: release
        run: echo ::set-output name=tag::${GITHUB_REF/refs\/tags\/k8s\//}
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Get Go version
        run: echo "goversion=`egrep -i '^go [1-2][.][0-9]+$' go.mod | sed 's/go //' | sed 's/$/.x/'`" >> $GITHUB_ENV
        working-directory: ./k8s
      - name: Log in to GitHub Docker Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.cr-pat }}
      - name: Build Image
        uses: docker/build-push-action@v2
        with:
          context: ./k8s
          push: true
          tags: |
            ghcr.io/${{ github.repository }}:${{ steps.release.outputs.tag }}
            ghcr.io/${{ github.repository }}:latest
  
        