name: Go Lambda Image Build
on:
  workflow_call:
    secrets:
      iam-role:
        description: 'Role for AWS ECR access'
        required: true
      ecr-registry:
        description: 'AWS ECR Registry'
        required: true
    inputs:
      aws-region:
        description: 'AWS Region'
        default: 'eu-west-1'
        required: false
        type: string
      work-directory:
        description: 'Directorz of Go sources'
        default: './'
        required: false
        type: string
      artifact-name:
        description: 'File name of Go bin artifact'
        default: 'build_artifact_bin'
        required: false
        type: string
      ecr-path:
        description: 'Path prefix for ECR'
        default: ''
        required: false
        type: string
    
jobs:
  ect-image-build:
    name: AWS ECR Image Build
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Download Golang Binary
        uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.artifact-name }}
          path: ${{ inputs.work-directory }}
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.iam-role }}
          aws-region: ${{ inputs.aws-region }}
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
      - name: Build Image
        uses: docker/build-push-action@v6
        with:
          context: ${{ inputs.work-directory }}
          push: true
          tags: |
            ${{ secrets.ecr-registry }}/${{ inputs.ecr-path }}${{ github.repository }}:${{ github.sha }}
            ${{ secrets.ecr-registry }}/${{ inputs.ecr-path }}${{ github.repository }}:latest
        