on:
  workflow_call:
    inputs:
      work-directory:
        description: 'Directorz of Go sources'
        default: './'
        required: false
        type: string
      artifact-name:
        description: 'File name of Go bin artifact'
        default: 'build_artifact_bin'
        required: false
        type: string
      artifact-path:
        description: 'Upload path for Go bin artifact'
        default: 'build_artifact_bin'
        required: false
        type: string

jobs:
  go-build:
    name: Go Test & Binary Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Get Go version
        run: echo "goversion=`egrep -i '^go [1-2][.][0-9]+$' go.mod | sed 's/go //' | sed 's/$/.x/'`" >> $GITHUB_ENV
        working-directory: ./lambda
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.goversion }}
      - name: Build Binary
        run: CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -a -installsuffix cgo -v -o build_artifact_bin
        working-directory: ${{ inputs.work-directory }}
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ inputs.artifact-name }}
          path: ${{ inputs.artifact-path }}
          retention-days: 1
