
name: Multi Arch Image Build

on:
  workflow_call:
    
jobs:
  image_build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set version tag
        run: echo "VERSION_TAG=${GITHUB_REF#refs/tags/k8s/}" >> $GITHUB_ENV
        working-directory: ./k8s

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Release build
        uses: docker/build-push-action@v4
        with:
          context: ./k8s
          outputs: "type=registry,push=true"
          provenance: false
          platforms: linux/amd64,linux/arm64
          build-args: |
            Version=${{ env.VERSION_TAG }}
            GitCommit=${{ github.sha }}
          tags: |
            ghcr.io/${{ github.repository }}:${{ github.sha }}
            ghcr.io/${{ github.repository }}:${{ env.VERSION_TAG }}
            ghcr.io/${{ github.repository }}:latest
