
name: Multi Arch Image Build

on:
  workflow_call:
    inputs:
      work-directory:
        description: 'Directorz of Go sources'
        default: './'
        required: false
        type: string
      image-suffix:
        description: 'Optional image suffix'
        default: ''
        required: false
        type: string
    
jobs:
  image_build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set version tag
        run: echo "VERSION_TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
        working-directory: ${{ inputs.work-directory }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub Docker Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Release build
        uses: docker/build-push-action@v4
        with:
          context: ${{ inputs.work-directory }}
          outputs: "type=registry,push=true"
          provenance: false
          platforms: linux/amd64,linux/arm64
          build-args: |
            Version=${{ env.VERSION_TAG }}
            GitCommit=${{ github.sha }}
          tags: |
            ghcr.io/${{ github.repository }}${{ inputs.image-suffix }}:${{ github.sha }}
            ghcr.io/${{ github.repository }}${{ inputs.image-suffix }}:${{ env.VERSION_TAG }}
            ghcr.io/${{ github.repository }}${{ inputs.image-suffix }}:latest
