name: Go Package Release
on:
  workflow_call:

permissions:
  contents: read

jobs:
  test:
    name: Go Tests
    permissions:
      contents: read
    uses: ./.github/workflows/go.test.v2.yml

  release:
    name: Go Package Release
    needs: [test]
    if: github.ref == 'refs/heads/main'
    permissions:
      contents: write
    uses: ./.github/workflows/go.pkg.release.yml
