
name: Golang Protobuf Compile
on:
  workflow_call:
    secrets:
      cr-pat:
        description: 'Personal access token'
        required: true

jobs:
  compile-go:
    name: Compile for Golang
    runs-on: ubuntu-latest
    container: 
      image: ghcr.io/tommzn/github-ci/images/protobuf-compiler-go
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.cr-pat }}
    steps:
      - name: Protoc Version
        run: |
          protoc --version 
          go version
      - name: Checkout Protobuf event defs
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
      - name: Compile
        run: |
          export GOROOT=/usr/local/go
          export GOPATH=/root/go
          export GOBIN=$GOPATH/bin
          export PATH=$PATH:$GOROOT:$GOPATH:$GOBIN
          protoc --go_out=./ *.proto
        