name: Go Package Release
on:
  workflow_call:

jobs:
  test:
    name: Go Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Get Go version
        run: echo "goversion=`egrep -i '^go [1-2][.][0-9]+$' go.mod | sed 's/go //' | sed 's/$/.x/'`" >> $GITHUB_ENV
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.goversion }}
      - name: Run tests
        run: go test -race -covermode atomic -coverprofile=covprofile ./...
      - name: Coveralls
        uses: coverallsapp/github-action@v2
        with:
          file: covprofile

  release:
    name: Go Package Release
    needs: [test]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: go-semantic-release/action@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}