
name: Golang Protobuf Compile
on:
  workflow_call:
    secrets:
      cr-pat:
        description: 'Personal access token'
        required: true
      slack-channel:
        description: 'Slack channel id a success/error message should be send to.'
        required: false
      slack-webhook:
        description: 'Slack webhock for publishing messages.'
        required: false
      slack-bottoken:
        description: 'Slack bot toekn for publishing messages.'
        required: false
    inputs:
      upload-artifact:
        type: boolean

jobs:
  compile-go:
    name: Compile for Golang
    runs-on: ubuntu-latest
    container: 
      image: ghcr.io/tommzn/github-ci/images/protobuf-compiler-go-alpine
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.cr-pat }}
    steps:
      - name: Protoc Version
        run: |
          protoc --version 
          go version
      - name: Checkout Protobuf event defs
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
      - name: Compile
        run: |
          protoc --go_out=./ *.proto
      - name: Upload Golang artifacts
        if: inputs.upload-artifact
        uses: actions/upload-artifact@v2
        with:
          name: golang-events
          path: ./*.pb.go
          retention-days: 1
      - name: Slack Notify
        if: always()
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_CHANNEL: ${{ secrets.slack-channel }}
          SLACK_COLOR: ${{ job.status }}
          SLACK_TITLE: "Protobuf Compile"
          SLACK_MESSAGE: "${{ job.status }} on protobuf compile for ${{ github.ref_type }}: ${{ github.ref_name }}"
          SLACK_USERNAME: "GitHub Notifications"
          SLACK_WEBHOOK: ${{ secrets.slack-webhook }}
          MSG_MINIMAL: event,actions url,commit 

      
        
        