
name: Golang Protobuf Compile
on:
  workflow_call:
    secrets:
      cr-pat:
        description: 'Personal access token'
        required: true
      slack-channel:
        description: 'Slack channel id a success/error message should be send to.'
        required: false
      slack-webhook:
        description: 'Slack webhock for publishing messages.'
        required: false
      slack-bottoken:
        description: 'Slack bot toekn for publishing messages.'
        required: false
    inputs:
      upload-artifact:
        type: boolean

jobs:
  compile-go:
    name: Compile for Golang
    runs-on: ubuntu-latest
    container: 
      image: ghcr.io/tommzn/github-ci/images/protobuf-compiler-go-alpine
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.cr-pat }}
    steps:
      - name: Protoc Version
        run: |
          protoc --version 
          go version
      - name: Checkout Protobuf event defs
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
      - name: Compile
        run: |
          protoc --go_out=./ *.proto
      - name: Send Slack Message (Failed)
        if: failure()
        uses: slackapi/slack-github-action@v1.23.0
        with:
          channel-id: ${{ secrets.slack-channel }}
          payload: |
            {
              "text": "Protobuf Compile: ${{ job.status }}",
              "blocks": [
                {
                  "type": "header",
                  "text": {
                    "type": "plain_text",
                    "text": ":x: Protobuf Compile: ${{ job.status }}"
                  }
                },
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "${{ github.repository }}"
                  }
                },
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "${{ github.ref_type }}: ${{ github.ref_name }}"
                  }
                },
                {
                  "type": "divider"
                },
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "<${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|View at GitHub Actions> | <${{ github.event.head_commit.url }}|Commit: ${{ github.event.head_commit.id }}>"
                  }
                }
              ]
            }
        env:
          SLACK_BOT_TOKEN: ${{ secrets.slack-bottoken }}
      - name: Send Slack Message (Success)
        if: success()
        uses: slackapi/slack-github-action@v1.23.0
        with:
          channel-id: ${{ secrets.slack-channel }}
          payload: |
            {
              "text": "Protobuf Compile: ${{ job.status }}",
              "blocks": [
                {
                  "type": "header",
                  "text": {
                    "type": "plain_text",
                    "text": ":white_check_mark: Protobuf Compile: ${{ job.status }}"
                  }
                },
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "${{ github.repository }}"
                  }
                },
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "${{ github.ref_type }}: ${{ github.ref_name }}"
                  }
                },
                {
                  "type": "divider"
                },
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "<${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|View at GitHub Actions> | <${{ github.event.head_commit.url }}|Commit: ${{ github.event.head_commit.id }}>"
                  }
                }
              ]
            }
        env:
          SLACK_BOT_TOKEN: ${{ secrets.slack-bottoken }}
      - name: Upload Golang artifacts
        if: inputs.upload-artifact
        uses: actions/upload-artifact@v2
        with:
          name: golang-events
          path: ./*.pb.go
          retention-days: 1
        
        